# ResaleFlatPricesBasedonApprovalDate2000Feb2012:
#   dataset_id: "d_43f493c6c50d54243cc1eab0df142d6a"
#   expected_cols: 
#     - "month"
#     - "town"
#     - "flat_type"
#     - "block"
#     - "street_name"
#     - "storey_range"
#     - "floor_area_sqm"
#     - "flat_model"
#     - "lease_commence_date"
#     - "resale_price"
ResaleFlatPricesBasedonRegistrationDateFromMar2012toDec2014:
  dataset_id: "d_2d5ff9ea31397b66239f245f57751537"
  expected_cols: 
    - "month"
    - "town"
    - "flat_type"
    - "block"
    - "street_name"
    - "storey_range"
    - "floor_area_sqm"
    - "flat_model"
    - "lease_commence_date"
    - "resale_price"
ResaleFlatPricesBasedonRegistrationDateFromJan2015toDec2016:
  dataset_id: "d_ea9ed51da2787afaf8e51f827c304208"
  expected_cols: 
    - "month"
    - "town"
    - "flat_type"
    - "block"
    - "street_name"
    - "storey_range"
    - "floor_area_sqm"
    - "flat_model"
    - "lease_commence_date"
    - "remaining_lease"
    - "resale_price"